### ISSUE TITLE
实测在小型攻击后突然大流量攻击会导致漏假人

### ISSUE THREAD

**Issue by StarryCamile** [CatMoe/AkaneField#53]
在AkaneField zzZ状态突然攻击会漏1-3假人

**Comment by FallenCrystal** [comment]
idk如何解决说实话 我需要的是一个能减缓机器人攻击带来影响的插件 而不是一个为了完全抵抗机器人而生的插件
而且樱花星海有Limbo 所以至少对于我来说是没什么影响的 但其它服务器的话
我不知道该怎么做 如果你可以提供PR 那么则感激不尽

> AkaneField皆在于保持兼容性的同时提供更好的防护 所以我为什么不篡改管道监听 或折腾在上面内置Limbo服务器
